<?php

use MediaWiki\Maintenance\Maintenance;
use MediaWiki\MediaWikiServices;

require_once __DIR__ . '/Maintenance.php';

class MassPageGen extends Maintenance {
    public function __construct() {
        parent::__construct();
        $this->addDescription( 'Update a massive number of pages for load testing' );
        $this->addOption( 'count', 'Number of pages to update', false, true );
        $this->addOption( 'start', 'Starting index', false, true );
    }

    public function execute() {
        global $wgDisableSearchUpdate, $wgEnableParserCache;
        
        // 1. Disable search index updates (massive time saver)
        $wgDisableSearchUpdate = true;
        
        // 2. Disable parser caching for this script run
        $wgEnableParserCache = false;
        
        $count = (int)$this->getOption( 'count', 3 );
        $start = (int)$this->getOption( 'start', 0 );
        
        $services = MediaWikiServices::getInstance();
        $titleFactory = $services->getTitleFactory();
        $wikiPageFactory = $services->getWikiPageFactory();
        $contentHandlerFactory = $services->getContentHandlerFactory();
        
        $user = User::newSystemUser( 'Maintenance script', [ 'steal' => true ] );
                
        $this->output( "Starting update of $count pages starting from $start...\n" );

        for ( $i = $start; $i < ($start + $count); $i++ ) {
            $title = $titleFactory->newFromText( "Load_Test_Page_$i" );
            $page = $wikiPageFactory->newFromTitle( $title );
            
            $contentHandler = $contentHandlerFactory->getContentHandler( 'wikitext' );
            
            // Modify your content generation here as needed
            $content = $contentHandler->makeContent("(Source: {{PAGENAME}})\n \n{{LoadTestInclude}}\n\n(Generated by MassPageGen.php)", $title);

            // CHANGED: Replaced EDIT_NEW with EDIT_UPDATE
            $status = $page->doUserEditContent(
                $content,
                $user,
                "Mass update for load testing",
                EDIT_UPDATE | EDIT_SUPPRESS_RC | EDIT_DEFER_UPDATES
            );

            if ( !$status->isOK() ) {
                $this->output( "Failed to update page $i: " . $status->getWikiText( false, false, 'en' ) . "\n" );
            }

            if ( $i % 10 === 0 ) {
                $this->output( "Updated $i\n");
            }

            // Memory management for large batches
            if ( $i % 1000 === 0 && $i !== $start ) {
                $this->output( "Updated batch ending at $i...\n" );
                
                // Clear link cache
                $services->getLinkCache()->clear();
                
                // NEW: Execute deferred updates to prevent memory exhaustion
                DeferredUpdates::doUpdates(); 
            }
        }

        // Catch any remaining deferred updates after the loop finishes
        DeferredUpdates::doUpdates();
        $this->output( "Done.\n" );
    }
}

$maintClass = MassPageGen::class;
require_once RUN_MAINTENANCE_IF_MAIN;

?>